
set(ENABLED_GEMS
    Game
    Atom
    AudioSystem
    AWSCore
    CameraFramework
    DebugDraw
    EditorPythonBindings
    EMotionFX
    GameState
    ImGui
    LandscapeCanvas
    LyShine
    Multiplayer
    PhysX
    PrimitiveAssets
    SaveData
    ScriptCanvasPhysics
    ScriptEvents
    StartingPointInput
    TextureAtlas
    WhiteBox
    AWSClientAuth
    AWSGameLift
    AWSMetrics
    Achievements
    AssetMemoryAnalyzer
    AssetValidation
    Atom_RPI
    Atom_Bootstrap
    Atom_AtomBridge
    Atom_Component_DebugCamera
    Atom_Feature_Common
    AtomFont
    AtomImGuiTools
    ImageProcessingAtom
    MaterialEditor
    AtomLyIntegration
    Atom_RHI
    Atom_RHI_DX12
    Atom_RHI_Metal
    Atom_RHI_Null
    Atom_RHI_Vulkan
    AtomShader
    AtomToolsFramework
    AtomTressFX
    AtomViewportDisplayIcons
    AtomViewportDisplayInfo
    Camera
    CertificateManager
    CommonFeaturesAtom
    DevTextures
    EMotionFX_Atom
    ExpressionEvaluation
    FastNoise
    GameStateSamples
    GradientSignal
    GraphCanvas
    GraphModel
    HttpRequestor
    ImguiAtom
    LocalUser
    Maestro
    Metastream
    Microphone
    MultiplayerCompression
    Blast
    NvCloth
    LmbrCentral
    PhysXDebug
    PrefabBuilder
    PythonAssetBuilder
    QtForPython
    SceneProcessing
    ScriptCanvas
    ScriptCanvasDeveloperGem
    ScriptCanvasTesting
    ScriptedEntityTweener
    StartingPointCamera
    SurfaceData
    TickBusOrderViewer
    Twitch
    UiBasics
    Vegetation
    AudioEngineWwise
    VideoPlaybackFramework
)
